liao_field_path <- "~/data/n2o_liao/org/Global_change_biology_GCB-22-1572_primary_field_data.csv"
liao_pot_path <- "~/data/n2o_liao/org/Global_change_biology_GCB-22-1572_primary_pot_data.csv"
cui_path <- "~/data/n2o_cui_naturefood/43016_2021_384_MOESM3_ESM.csv"
cui_fallow_path <- "~/data/n2o_cui_naturefood/43016_2021_384_MOESM3_ESM_fallow.csv"
hortnagl_path <- "~/data/n2o_hortnagl_gcb/n2o_hortnagl_gcb.csv"
xuri_path <- "~/data/n2o_xuri/xuri_newphy.csv"
allpredictors <- "~/data/n2o_Yunke/final_forcing/siteinfo_predictors.csv"
fapar3g_df_zhu <- "~/data/n2o_Yunke/final_forcing/siteinfo_measurementyear_fapar3g_zhu.csv"
lpx_n2o <- "~/data/n2o_Yunke/final_forcing/LPX_annual_n2o.csv"
forest_cover <- "~/data/n2o_Yunke/final_forcing/forestcover_site.csv"
output_EF_path <- "~/data/n2o_Yunke/final_forcing/EF_database.csv"
output_n2o_siteinfo_path <- "~/data/n2o_Yunke/final_forcing/n2o_siteinfo.csv"
output_path <- "~/data/n2o_Yunke/final_obs_dataset/obs_field_dataset.csv"

df1_path <- "~/data/n2o_wang_oikos/n2o_tables1.csv"
fapar3g_df_zhu_path <- "~/data/n2o_Yunke/final_forcing/co2_siteinfo_measurementyear_fapar3g_zhu.csv"
climates_soil_path <- "~/data/n2o_Yunke/final_forcing/co2_siteinfo_predictors.csv"
df2_path <- "~/data/n2o_wang_oikos/n2o_tables2.csv"
output_co2_path <- "~/data/n2o_Yunke/final_obs_dataset/obs_eCO2_dataset.csv"
output_warming_path <- "~/data/n2o_Yunke/final_obs_dataset/obs_warming_dataset.csv"


#Data path for further users (geco-users, and readers) to run:
#liao_field_path <- "/data/archive/n2o_liao/Global_change_biology_GCB-22-1572_primary_field_data.csv"
#liao_pot_path <- "/data/archive/n2o_liao/Global_change_biology_GCB-22-1572_primary_pot_data.csv"
#cui_path <- "/data/archive/n2o_cui_naturefood/43016_2021_384_MOESM3_ESM.csv"
#cui_fallow_path <- "/data/archive/n2o_cui_naturefood/43016_2021_384_MOESM3_ESM_fallow.csv"
#hortnagl_path <- "/data/archive/n2o_hortnagl_gcb/n2o_hortnagl_gcb.csv"
#xuri_path <- "/data/archive/n2o_xuri/xuri_newphy.csv"
#allpredictors <- "/data/archive/n2o_Yunke/final_forcing/siteinfo_predictors.csv"
#fapar3g_df_zhu <- "/data/archive/n2o_Yunke/final_forcing/siteinfo_measurementyear_fapar3g_zhu.csv"
#lpx_n2o <- "/data/archive/n2o_Yunke/final_forcing/LPX_annual_n2o.csv"
#forest_cover <- "/data/archive/n2o_Yunke/final_forcing/forestcover_site.csv"
#output_path <- "/data/archive/n2o_Yunke/final_obs_dataset/obs_field_dataset.csv"
#df1_path <- "/data/archive/n2o_wang_oikos/n2o_tables1.csv"
#fapar3g_df_zhu_path <- "/data/archive/n2o_Yunke/final_forcing/co2_siteinfo_measurementyear_fapar3g_zhu.csv"
#climates_soil_path <- "/data/archive/n2o_Yunke/final_forcing/co2_siteinfo_predictors.csv"
#df2_path <- "/data/archive/n2o_wang_oikos/n2o_tables2.csv"
#output_co2_path <- "/data/archive/n2o_Yunke/final_obs_dataset/obs_eCO2_dataset.csv"
#output_warming_path <- "/data/archive/n2o_Yunke/final_obs_dataset/obs_warming_dataset.csv"

